version: '3'

services:
  mysql-book-store:
    image: mysql:latest
    restart: always
    container_name: mysql-book-store
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - 3310:3306
    volumes:
      - ../docker/mysql-book-store/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_USER=joe
      - MYSQL_PASSWORD=qwer1234
      - MYSQL_DATABASE=bookstore
      - TZ=Asia/Taipei
    command:
      - 'mysqld'
      - '--character-set-server=utf8'
      - '--collation-server=utf8_bin'
      - '--default-time-zone=+08:00'
      - '--skip-character-set-client-handshake'
      - '--default-authentication-plugin=mysql_native_password'
      - '--log-bin-trust-function-creators=1'
      - '--lower_case_table_names=1'
