spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/bookstore?chartacterEnconding=UTF-8
    username: root
    password: qwer1234
    #thymeleaf 熱部屬
  thymeleaf:
    cache: false
  #修改靜態資源的訪問路徑
  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir}

##Mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.joe.springboot.model

#日誌
logging:
  level:
    root: info
    com.joe: debug

#上傳文件的路徑
photo:
  file:
    dir: D:\engineer\Code\bookstore\photos
